spring:
  application:
    # 指定微服务的名称
    name: eureka-consumer

server:
  port: 8004

eureka:
  client:
    serviceUrl:
      # 指定服务注册中心的位置
      defaultZone: http://localhost:8001/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8002/service-auth/user/curren